name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          echo ${TEST}
          echo ${TEST1}
        env:
          TEST: -n \"b c\"
          TEST1: |
            -n "b c"
